name: Validate Renovate Config

on:
  push:
    paths:
      - ./github/workflows/validate-config.yml
      - '**/renovate.json5'
  pull_request:
    paths:
      - ./github/workflows/validate-config.yml
      - '**/renovate.json5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: "1"
      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "24"
      - name: Validate Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator --strict **/renovate.json5
